#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

#      File Name: cdRoot
#      Author: emlyq@hotmail.com
#      Created on: Mon May 16 11:22:53 CST 2016

CUR_PATH=`pwd`
echo "CUR_PATH = ${CUR_PATH}"
echo "HOME = ${HOME}"
get_taget()
{
	while [ TRUE ]
	do
		cd ..
		tmp_path=`pwd`
		echo "tmp_path = ${tmp_path}"
		if [ -d "${tmp_path}/.repo" ];then
			cd ${tmp_path}
			break
		elif [ "${tmp_path}" = "$HOME" ];then
			cd ${CUR_PATH}
			break
		fi
	done
}

get_taget
chdir ../..
