#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

#      File Name: hibuild
#      Author: emlyq@hotmail.com
#      Created on: Wed Oct 12 09:41:19 UTC 2016

#set -x
source ~/9-scripts/godir.sh
# make ARCH=arm hi3536_svr2730_defconfig
# make ARCH=arm hi3536_medt100_defconfig
go linux-3.10.0
make -j8 uImage ARCH=arm CROSS_COMPILE=/opt/arm-hisiv300-linux/bin/arm-hisiv300-linux-uclibcgnueabi-
scp arch/arm/boot/uImage root@172.16.104.191:/opt/tftpboot/uImage-hi3536
# make savedefconfig && mv defconfig arch/arm/configs/hi3536_svr2730_defconfig
cp arch/arm/boot/uImage arch/arm/boot/uImage-`date "+%Y-%m-%d-%H%M%S"`
cp arch/arm/boot/uImage uImage-hi3536
