#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

#      File Name: mh
#      Author: emlyq@hotmail.com
#      Created on: Wed Aug  2 02:06:18 UTC 2017

echo "make CROSS_COMPILE=/opt/hisi-linux/x86-arm/arm-hisiv500-linux/bin/arm-hisiv500-linux-uclibcgnueabi-"
echo "make ARCH=arm CROSS_COMPILE=/opt/hisi-linux/x86-arm/arm-hisiv500-linux/bin/arm-hisiv500-linux-uclibcgnueabi- medt100_hi3519_defconfig"
echo "make ARCH=arm hi3536_its200_defconfig"
echo "make ARCH=arm hi3536_svr2730_defconfig"
echo "make ARCH=arm hi3536_medt100_defconfig"
echo "make its200_config CROSS_COMPILE=/opt/arm-hisiv300-linux/bin/arm-hisiv300-linux-uclibcgnueabi-"
echo "make svr2730_config CROSS_COMPILE=/opt/arm-hisiv300-linux/bin/arm-hisiv300-linux-uclibcgnueabi-"
echo "make medt100_config CROSS_COMPILE=/opt/arm-hisiv300-linux/bin/arm-hisiv300-linux-uclibcgnueabi-"
echo "ultron 666666"
echo "make menuconfig ARCH=arm CROSS_COMPILE=/opt/hisi-linux/x86-arm/arm-hisiv300-linux/bin/arm-hisiv300-linux-uclibcgnueabi-"
echo "make ARCH=arm CROSS_COMPILE=/opt/hisi-linux/x86-arm/arm-hisiv300-linux/bin/arm-hisiv300-linux-uclibcgnueabi- hi3516a_full_defconfig"
echo "make ARCH=arm hi3516a_full_defconfig"
echo "make -j8 ARCH=arm uImage CROSS_COMPILE=arm-hisiv610-linux-"
