#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

#      File Name: myMv
#      Author: emlyq@hotmail.com
#      Created on: Mon May 16 11:24:35 CST 2016

# we have less than 2 arguments. Print the help text:
if [ $# -lt 2 ] ; then
	echo "Usage: $0 'oldfile' 'newfile'"
	echo ""
	exit 1
fi

mv $1 $2
OLD_FILE_NAME=$(echo "$1" | sed -r 's/.*\///g')
NEW_FILE_NAME=$(echo "$2" | sed -r 's/.*\///g')
sed -i '21d' $2
sed -i "21 i#      File Name: ${NEW_FILE_NAME}" $2



#sed -i "s/#      File Name: ${OLD_FILE_NAME}/#      File Name:/g" $2
#sed -i "s/#      File Name:/#      File Name: ${NEW_FILE_NAME}/g" $2
