#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

#      File Name: repostart
#      Author: emlyq@hotmail.com
#      Created on: Wed Apr 19 14:28:41 CST 2017


local_path=`pwd`
projs=`find ./packages -name .git  | sed 's/\/.git//g'`

for i in $projs
do
	cd $i
	dev_branch=`git branch -av | grep '>' | awk -F/ '{ print $4 }'`
	echo "$i ---> ${dev_branch}"
	git checkout -b ${dev_branch}
	cd ${local_path}
done
